### ISSUE TITLE
 First Alpha Release Checklist

### ISSUE THREAD

**Issue by Davoleo** [Davoleo/Metallurgy-4-Reforged#12]
Checklist:
- [x] Armors (alloys)
- [x] Tile Entities #8 
- [x] All the crafting recipes
- [x] Tools (alloys)
- [x] Tool effects
- [x] Armor effects
- [x] Tooltips [Needs tool effects and armor effects to be completed first]
- [x] Textures
- [x] All the metal dusts
- [x] All the molten metals
- [x] Add Name to tools 
- [x] Fix issues with textures : Kalendrite Armor and Atlarus Armor
- [x] Inventory side integration (hopper/cables) [#23]
- [x] GUI Rework & Fixes
- [x] Implement harvestLevel to all blocks
- [x] Add Armor and Recipes
- [x] Add Road

If you want a more code-specific list, search for `TODO` in the repository
