### ISSUE TITLE
Features Checklist

### ISSUE THREAD

**Issue by HurtsAsHell** [Davoleo/Metallurgy-4-Reforged#47]
Checklist:
- [x] JEI Integration
  - [x] Crusher
  - [x] Alloyer
  - [x] How to create Tar Ore ( Information Label ) @Davoleo 
- [x] Tinkers' Construct Integration
  - [x] Fix color of fluids [ Tinker-Branch ] ( Haderoth )
  - [x] Add Smeltery Crafting
  - [x] Add Part Stats _[ Not Certain ]_
  - [x] Add Bow Part
  - [x] Add Custom HarvestLevel name
  - [x] Add Traits
  - [x] Remove Tools from materials that don't usually have tools
- [x] Construct's Armory Integration
- [x] Adjust Enhanced lighters range to the player distance
- [x] Add "Full set Effect : " to tooltips https://github.com/Davoleo/Metallurgy-4-Reforged/commit/d0b67fc75ded241e1aa09f701a943d1fe8e26f87
- [x] Nerf Adamantine armor #92 
- [x] Add fuel and material to Tinker/Metallurgy : T*****e ( 2300+ C° ) [ **No Spoiler** ]
- [x] Configuration Files
 - [x] Fix #77 
 - [x] Effects and mod customization
 - [x] Enable and Disable features
 - [x] Ore Generation configuration
- [x] Add tar in World Crafting
- [x] Krik Ingot
  - [x] Krik Armor with Custom Effect
- [x] Metal Nuggets (?) =)  #103 
- [x] Invisibility Shield
- [x] new Tile Entity : Sublimation Chamber
- [x] CraftTweaker Integration
- [ ] Create a Custom Mob **Leprechaun**
- [ ] Skögul - means high-towering in Old Norse, often related to Valkyries and Gods. ( Matpac ) #83 
- [ ] Create "L Boots" **No Spoiler** 
- [x] ~Add a build number to the version~
- [x] ~Tweak Tile Entity Slots Shape~
- [x] ~API (?) #121~
- [ ] Make Advancements
- [ ] Haderoth gauntlets (or something similar, like claws) [ Matpac ]

**This List is not final it can be changed in the future**

**Comment by Klazkin** [comment]
@HurtsAsHell Do we need simplified GUI textures to fit JEI?

**Comment by Davoleo** [comment]
Didn't see how it looks yet, but probably

**Comment by HurtsAsHell** [comment]
@Klazkin not for now

**Comment by Davoleo** [comment]
I keep losing track of this issue, I'm just gonna close it and add everything to the dev project
