### ISSUE TITLE
Checklist of TODO in 1.12.2

### ISSUE THREAD

**Issue by HurtsAsHell** [Davoleo/Metallurgy-4-Reforged#96]
- [x] Armor/weapon tooltips are unclear or worded awkwardly, **fix it** 137eb29dd76d21068eb65b394e244989631b5f47

- [x] Turning off effects for armors/weapons in the config does not disable the tooltips, **Fix it**
  - [x] Armor Tooltips 8af861ceadb8629e50b382af1cd906cb89b7ab81
  - [x] Tool/Sword Tooltips 7fced519bfadceaa241b98975791dd01f31d7849
- [x] "Desichalkos Sword: chance to inflict a random negative effect on hit" **Add it** d6455d4c71db2da7a5c64a2f0bd50638bd6119b8
 
- [x] Add  a lang record for custom Tinker Traits
  - [x] Obscure Trait
  - [x] Vulcan Trait
- [x] Add Crafting to Gauntlet

Thanks Luke616 helping us with tests

**Comment by Davoleo** [comment]
We'll temporarily disable adamantine for the next release, so that people can test the mod without something overpowered

**Comment by Davoleo** [comment]
Moved everything else to #47
